---
title: "Amino acids in 100g of Proteins"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(readr)
library(readxl)
library(plotly)
```

```{r}
data <- read_excel("C:/Users/earls/OneDrive/Documents/RProjects/RProjects/MyProjects/Diet and Health/Amino acids/Data/Safe levels of protein intake.xlsx", sheet=3)

data <- data.frame(data)
```

```{r}
class(data)
```

```{r}
View(data)
```

```{r}
colnames(data)
```

```{r}
skimr::skim(data)
```

```{r}
animal_prot <- data %>% 
  slice(1:9) %>%
  mutate(category = "Animal") %>%
  rename(
    "prot_g" = "prot.g.",
    "try_mg" = "try.mg.",
   "thr_mg" = "thr.mg.",
   "iso_mg" = "iso.mg.",
   "leu_mg" = "leu.mg.",
   "lys_mg" = "lys.mg.",
   "met_mg" = "met.mg.",
   "phe_mg" = "phe.mg.",
   "val_mg" = "val.mg.",
   "arg_mg" = "arg.mg.",
   "his_mg" = "his.mg."
  ) %>%
  pivot_longer(cols = ends_with("mg"), names_to = "amino_acids", values_to = "amount_mg") #%>% 
  #mutate(percentage = (prot_g/100)*100)
```

```{r}
View(animal_prot)
```

```{r}
plant_prot <- data %>% 
  slice(10:30) %>% 
  mutate(category = "plant") %>% 
  rename(
     "prot_g" = "prot.g.",
    "try_mg" = "try.mg.",
   "thr_mg" = "thr.mg.",
   "iso_mg" = "iso.mg.",
   "leu_mg" = "leu.mg.",
   "lys_mg" = "lys.mg.",
   "met_mg" = "met.mg.",
   "phe_mg" = "phe.mg.",
   "val_mg" = "val.mg.",
   "arg_mg" = "arg.mg.",
   "his_mg" = "his.mg."
  ) %>%
  pivot_longer(cols = ends_with("mg"), names_to = "amino_acids", values_to = "amount_mg")
```

```{r}
View(plant_prot)
```

```{r}
data_combined <- bind_rows(animal_prot, plant_prot)
```

```{r}
View(data_combined)
```

```{r}
colnames(data_combined)
```

```{r}
p<- ggplot(data_combined, aes(prot_g, food, fill = category))+
    geom_bar(stat = "identity", position = "dodge") +  # Horizontal grouped bars
    labs(
        title = "Amount of Proteins per 100g of Food Type",
        x = "Amount (mg)",
        y = "Food"
    ) +
    scale_fill_brewer(palette = "Set3") +  # Optional color palette
    theme_minimal()
```

```{r}
p
```

```{r}
ggplotly(p)
```

```{r}
display.brewer.all()
```