---
title: "Test Rig Purging and Evaporative Cooling"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(readr)
library(readxl)
library(tidyr)
```

```{r}
#First data to be used to visualize heating
data <- read_excel("C:/Users/earls/Downloads/Block B1 Cycle 6 Desorption.xlsx", sheet=1)
# Actual path
# "C:/Users/earls/OneDrive/Documents/RProjects/MyProjects/OctWork/Rig tests/Data/Block B1 Cycle 6 Desorption.xlsx"
```

```{r}
View(data)
```

```{r}
colnames(data)
```

```{r}
class(data)
```
```{r}
data1 <- data %>%
  select(timeSeconds, pressure, blockTemp3, blockTemp4) %>%
  slice(1001:1042) %>%
  pivot_longer(cols = c(blockTemp3, blockTemp4), names_to = "temperature", values_to = "values")
```

```{r}
data2 <- data %>%
  select(timeSeconds, pressure, blockTemp3, blockTemp4) %>%
  slice(1001:1042)
```

```{r}
View(data1)
```

```{r}
ggplot(data1, aes(x = timeSeconds, y= values, color = temperature))+
geom_point()
```

```{r}
ggplot(data2, aes(x = timeSeconds, y= blockTemp3, color = 'maroon'))+
geom_point()
```

======================
## Predicting the heating rate
```{r}
data2_mod <- lm (blockTemp3 ~ timeSeconds, data2)
coef(data2_mod)

broom::tidy(data2_mod)
```

## Prediction of heating rate
Train/test split
```{r}
library(rsample)
```

```{r}
data2_split <- initial_split(data2)
data2_train <- training(data2_split)
data2_test <- testing(data2_split)
```

### Model fitting
```{r}
model <- lm(blockTemp3 ~ timeSeconds, data= data2_train)
```

### Prediction
```{r}
prediction <- predict(model, data= data2_test)
prediction <- prediction[1:nrow(data2_test)]  # Truncate if too long

length(prediction)

data2_test <- data2_test %>%
  mutate(predvalues = prediction)

#data1_test
#coef(model)

ggplot(data2_test)+
geom_line(aes(timeSeconds, predvalues), size=3, color = "red", alpha=0.5)+
geom_point(aes(timeSeconds, blockTemp3), size=5, color = "green", alpha=0.75)+
geom_point(data= data2, aes(timeSeconds, blockTemp3), alpha=0.5)
```