---
title: "Mona Vacuum Test"
output:
  html_document:
    df_print: paged
---

```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(readxl)
library(plotly)
library(tidyr)
```

```{r}
data <- read_excel("C:/Users/earls/OneDrive/Documents/RProjects/MyProjects/OctWork/Rig tests/Data/Block B1 Cycle 6 Desorption.xlsx", sheet=1)
```

```{r}
View(data)
```

```{r}
colnames(data)
```

```{r}
data1 <- data %>%
  select(timeMillis, timeSeconds, pressure, blockTemp1, blockTemp2, blockTemp3, blockTemp4, CO2Perc, O2Perc)
```

```{r}
View(data1)
```

```{r}
colnames(data1)
```

## Use Patchwork to combine several graphs together
```{r}
library(patchwork)

```

```{r}
p1 <- ggplot(data1, aes(timeSeconds, pressure))+
  geom_line(color="maroon")+
  labs(y= "pressure", x = NULL)+
  theme_minimal()

p2 <- ggplot(data1, aes(timeSeconds, CO2Perc))+
  geom_line(color="blue4")+
  labs(y = "CO2 (%)", x=NULL)+
  theme_minimal()

p3 <- ggplot(data1, aes(timeSeconds, O2Perc))+
  geom_line(color = "seagreen4")+
  labs(y="O2 (%)", x = NULL)+
  theme_minimal()
```

## Combine the graphs vertically
```{r}
po <- p1/p2/p3
```

```{r}
po
```

```{r}

```

```{r}
ggsave("With_Purging_Process.jpeg", po)
```

## Combine graphs to share a common x-axis
### Use ggplot2 with faceting
### Convert data to a long-format
### using tidyr

```{r}
long_data <- data1 %>% 
  pivot_longer(cols= c(blockTemp3, pressure, CO2Perc, O2Perc), names_to = "variable", values_to = "value") %>%
  slice(1789:16578)
```

```{r}
View(long_data)
```

### Using ggplot2 with facets

```{r}
po <- ggplot(long_data, aes(x=timeSeconds, y=value, color=variable))+
  geom_line()+
  facet_wrap(~variable, scales = "free_y", ncol=1)+
  labs(x="Time", y="Value")+
  theme_minimal()
```

```{r}
class(po)
```

```{r}
po1 <- ggplotly(po)
```

```{r}
library(htmlwidgets)

saveWidget(po1, "purging_step_interactive.html", selfcontained = TRUE)
```

```{r}
ggplot(long_data, aes(x = timeSeconds, y = value, color = variable)) +
  geom_line(linewidth = 1) +
  labs(x = "Time", y = "Value", color = "Variable") +
  theme_minimal() +
  theme(legend.position = "top")

```


## ggplot with dual y-axes
```{r}
#scale the data
data1$scaledCO2 <- data1$CO2Perc*10
data1$scaledO2 <- data1$O2Perc*45


ggplot(data1, aes(x = timeSeconds)) +
    geom_line(aes(y = pressure, color = "Pressure"), size = 1) +
    geom_smooth(aes(y = scaledO2, color = "O2 Concentration"), size = 1) +
    #geom_line(aes(y = scaled_O2, color = "O2 Concentration"), linetype = "dotted", size = 1) +
    scale_y_continuous(
    name = "Pressure (units)",  # Left y-axis
    sec.axis = sec_axis(~./45, name = "Concentration (%)")  # Right y-axis
    ) +
    labs(x = "Time", color = "Variable") +
    theme_minimal() +
    theme(legend.position = "top")
```

```{r}
#scale the data
data1$scaledCO2 <- data1$CO2Perc*1
data1$scaledO2 <- data1$O2Perc*45


ggplot(data1, aes(x = timeSeconds)) +
    geom_line(aes(y = blockTemp3, color = "Temperature"), size = 1) +
    geom_smooth(aes(y = scaledO2, color = "CO2 Concentration"), size = 1) +
    #geom_line(aes(y = scaled_O2, color = "O2 Concentration"), linetype = "dotted", size = 1) +
    scale_y_continuous(
    name = "Temp (degC)",  # Left y-axis
    sec.axis = sec_axis(~./1, name = "Concentration (%)")  # Right y-axis
    ) +
    labs(x = "Time", color = "Variable") +
    theme_minimal() +
    theme(legend.position = "top")
```


## Make p2 interactive
```{r}

```

## Temperatures
```{r}
long_data1 <- data1 %>%
  pivot_longer(c(starts_with("block")), values_to = "value", names_to = "variable") %>%
  slice(1:20000)

p3 <- ggplot(long_data1, aes(timeSeconds, y=value, color= variable))+
      geom_smooth(size=0.3)
      labs(
          x = "Time (seconds)",
          y = "Temperature (degC)",
          color = "Sensor Position"
      )+
      theme_minimal()+
      theme(legend.position = "top")
```

```{r}
View(long_data1)
```


```{r}
p4 <- ggplotly(p3)
```

```{r}
library(htmlwidgets)

#saveWidget()
saveWidget(p4, "temp_interactive.html", selfcontained = TRUE)


```

